project:
  type: website
  output-dir: docs

website:
  title: "Matthew S. Woodstock"
  site-url: https://mattwoodstock.com
  favicon: images/avatar.png
  twitter-card:
    creator: "@fishesarefrandz"
  description: |
    Matt Woodstock's Website.
  google-analytics: "G-07SZXPNSJZ"
  search: false
  navbar:
    background: primary
    foreground: secondary
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Publications
        href: publications.qmd
      - text: Research
        href: research.qmd
      - text: About Me
        href: about.qmd
    right:
      - icon: envelope
        href: mailto:matthew.woodstock@morgan.edu
      - icon: twitter
        href: https://twitter.com/fishesarefrandz
  page-footer:
    left: |
      <b>Matthew S. Woodstock, Ph.D.</b> <br>
      Postdoctoral Research Fellow<br>
      Morgan State University Patuxent Environmental and Aquatic Research Laboratory<br>
      © Copyright 2022 Matt Woodstock
    right: |
      <i class="fab fa-twitter"></i> <a href="https://twitter.com/fishesarefrandz">@fishesarefrandz</a> on Twitter <br>
      <i class="fab fa-github"></i> <a href="https://github.com/mwood078">mwood078</a> on GitHub <br>
      <i class="fas fa-envelope"></i> <a href="mailto:matthew.woodstock@morgan.edu">matthew.woodstock@morgan.edu</a><br>
      <i class="fas fa-map-marker-alt"></i> Maryland, USA
    border: true
    background: primary
format:
  html:
    theme: assets/theme.scss
    css: assets/styles.css
    include-after: |
      <link rel="stylesheet" href="assets/syntax-highlight.css">
      <link rel="stylesheet" href="assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>


